version: "2"
services:
  mydb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: fantasy
      POSTGRES_USER: fantasy
      POSTGRES_DB: fantasy
    volumes:
      - data-volume:/var/lib/postgresql/data
    ports:
      - "8000:5432"
  server:
#    image: server
    build: ./
    volumes:
      - ./coverage:/coverage-out
    command: bash -c "scripts/test.sh"
    depends_on:
      - mydb
volumes:
  data-volume:
